version: "3"

services:
  backend:
    build: ./backend
    container_name: ship-router-backend
    volumes:
      #in order to use your own data, mount your coastline file
      #here to data, instead of ./backend/data/antarctica-latest.osm.pbf
      - ./backend/data/antarctica-latest.osm.pbf:/data.pbf
    environment:
      - PORT=9090
      - DATAFILE=/data.pbf
      - NUMBER_OF_SPHERE_NODES=1000
    ports:
      - "9090:9090"

  frontend:
    build: ./frontend
    container_name: ship-router-frontend
    ports:
      - "8080:8080"
